from pymongo import MongoClient

def rename_food_groups_fdc(uri="mongodb://localhost:27017/", db_name="db_mongo", collection_name="fdc_backup"):
    """
    Ajoute un champ 'category_ca' basé sur le champ 'food_groups'
    selon un mapping défini pour le Guide alimentaire canadien (GAC).
    """
    # client = MongoClient(uri)
    # db = client[db_name]
    # col = db[collection_name]

    categories_and_code_ca = {
    "Légumes et Fruits":"1",
    "Fruits": "1120",
    "Légumes": "12", 
    "Légumes vert foncé": "1210",
    "Légumes jaune foncé ou orange": "1220",
    "Légumes féculents": "1230",
    "Autres légumes": "1240",
    "Grains entiers (100%)": "2100",
    "Aliments à grains entiers": "2210",
    "Aliments de blé entier": "2220",
    "Yogourts végétaux": "3200",
    "Fromages végétaux enrichis (qui contiennent suffisamment de protéines)": "3300",
    "Légumineuses": "3400",
    "Similis-viandes": "3500",
    "Noix et graines": "3600",
    "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)": "3700",
    "Aliments protéinés d’origine animale":"4",
    "Yogourts et kéfir": "4200",
    "Fromages": "4300",
    "Autres aliments à base de lait": "4400",
    "Viandes rouges": "4500",
    "Viandes de gibier": "4600",
    "Volaille et oiseaux sauvages": "4700",
    "Oeufs": "4710",
    "Poisson et fruits de mer": "4800",
    "Abats": "4900",
    "Boissons":"51",
    "Eau": "5110",
    "Boissons végétales enrichies (qui contiennent suffisamment de protéines)": "5120",
    "Boissons végétales non enrichies (qui contiennent suffisamment de protéines)": "5130",
    "Boissons végétales enrichies (qui ne contiennent pas suffisamment de protéines)": "5140",
    "Laits": "5150",
    "Jus de fruits": "5160",
    "Jus de légumes": "5170",
    "Autres boissons": "5180",
    "Autres aliments d’origine végétale (qui ne contiennent pas suffisamment de protéines)": "6100",
    "Condiments, sauces et vinaigrettes à faible teneur en matières grasses": "6200",
    "Autres grignotines": "6300",
    "Aliments à teneur plus élevée en sucre et/ou en gras": "6400",
    "Aliments enrichis qui ne sont pas à grains entiers et de blé entier": "6510",
    "Aliments non enrichis qui ne sont pas à grains entiers et de blé entier": "6520",
    "Viandes transformées": "6600",
    "Graisses et huiles non saturées": "7110",
    "Graisses et huiles saturées et trans": "7120",
    "Aliments pour bébés": "8100",
    "Substituts de repas et suppléments": "8200",
    "Boissons alcooliques": "8300",
    "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)": "8500",
    "Aliments et boissons non classés (en raison de données manquantes)": "9990"
}

    mapping = {
        "Alcohol": "Boissons alcooliques",
        "Alcoholic Beverages": "Boissons alcooliques",
        "All Noodles": "Aliments non enrichis qui ne sont pas à grains entiers et de blé entier",
        "American Indian/Alaska Native Foods": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Amino Acid Supplements": "Substituts de repas et suppléments",
        "Antioxidant Supplements": "Substituts de repas et suppléments",
        "Antipasto": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Aquatic Invertebrates/Fish/Shellfish/Seafood Combination": "Poisson et fruits de mer",
        "Ayurvedic Supplements": "Substituts de repas et suppléments",
        "Baby Foods": "Aliments pour bébés",
        "Baby/Infant  Foods/Beverages": "Aliments pour bébés",
        "Baby/Infant – Foods/Beverages": "Aliments pour bébés",
        "Bacon": "Viandes transformées",
        "Bacon, Sausages & Ribs": "Viandes transformées",
        "Baked Products": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Baking": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Baking Accessories": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Baking Additives & Extracts": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Baking Decorations & Dessert Toppings": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Baking Needs": "Aliments non enrichis qui ne sont pas à grains entiers et de blé entier",
        "Baking/Cooking Mixes (Frozen)": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Baking/Cooking Mixes (Perishable)": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Baking/Cooking Mixes (Shelf Stable)": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Baking/Cooking Mixes/Supplies": "Aliments non enrichis qui ne sont pas à grains entiers et de blé entier",
        "Baking/Cooking Mixes/Supplies Variety Packs": "Aliments non enrichis qui ne sont pas à grains entiers et de blé entier",
        "Baking/Cooking Supplies (Shelf Stable)": "Aliments non enrichis qui ne sont pas à grains entiers et de blé entier",
        "Bread": "Aliments à grains entiers",
        "Bread & Muffin Mixes": "Aliments à grains entiers",
        "Bread (Frozen)": "Aliments à grains entiers",
        "Bread (Shelf Stable)": "Aliments à grains entiers",
        "Bread - Incl. Buns And Rolls": "Aliments à grains entiers",
        "Breads & Buns": "Aliments à grains entiers",
        "Biscuits Chocolate": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Biscuits Cracker": "Aliments non enrichis qui ne sont pas à grains entiers et de blé entier",
        "Biscuits Kids": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Biscuits Plain/Sweet": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Biscuits/Cookies": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Biscuits/Cookies (Frozen)": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Biscuits/Cookies (Shelf Stable)": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Cakes - Sweet (Frozen)": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Cakes - Sweet (Shelf Stable)": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Cakes and Slices": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Cakes, Cupcakes, Snack Cakes": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Cakes/Slices/Biscuits": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Candy": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Cereal": "Aliments à grains entiers",
        "Cereal Grains and Pasta": "Aliments à grains entiers",
        "Breakfast Cereals": "Aliments à grains entiers",
        "Breakfast Cereals - Hot And Cold": "Aliments à grains entiers",
        "Breakfast Foods": "Aliments à grains entiers",
        "Breakfast Sandwiches, Biscuits & Meals": "Aliments non enrichis qui ne sont pas à grains entiers et de blé entier",
        "Cereal/Muesli Bars": "Autres grignotines",
        "Cereals Products - Ready to Eat (Shelf Stable)": "Aliments à grains entiers",
        "Cereals Products - Not Ready to Eat (Shelf Stable)": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Cereal Products - Ready to Eat (Perishable)": "Aliments à grains entiers",
        "Cheese": "Fromages",
        "Cheese - Block": "Fromages",
        "Cheese - Speciality": "Fromages",
        "Cheese/Cheese Substitutes": "Fromages",
        "Cream": "Autres aliments à base de lait",
        "Cream/Cream Substitutes": "Autres aliments à base de lait",
        "Butter & Spread": "Graisses et huiles non saturées",
        "Butter/Butter Substitutes": "Graisses et huiles non saturées",
        "Dairy Foods/Yoghurts": "Yogourts et kéfir",
        "Dairy and Egg Products": "Aliments protéinés d’origine animale",
        "Dairy/Egg Based Products / Meals": "Aliments protéinés d’origine animale",
        "Eggs": "Oeufs",
        "Egg Based Products / Meals - Not Ready to Eat (Frozen)": "Oeufs",
        "Beef - Prepared/Processed": "Viandes transformées",
        "Beef Products": "Viandes rouges",
        "Beef Sausages - Prepared/Processed": "Viandes transformées",
        "Chicken - Prepared/Processed": "Viandes transformées",
        "Chicken - Unprepared/Unprocessed": "Volaille et oiseaux sauvages",
        "Canned Meat": "Viandes transformées",
        "Canned Fish and Meat": "Poisson et fruits de mer",
        "Canned Seafood": "Poisson et fruits de mer",
        "Canned Tuna": "Poisson et fruits de mer",
        "Berries/Small Fruit": "Fruits",
        "Canned Fruit": "Fruits",
        "Canned Vegetables": "Autres légumes",
        "Canned/Dried Veges": "Autres légumes",
        "Chickpeas": "Légumineuses",
        "Dips/Hummus/Pate": "Légumineuses",
        "Deli Salads": "Autres légumes",
        "Beer": "Boissons alcooliques",
        "Beverages": "Boissons",
        "Drinks": "Boissons",
        "Drinks - Juices, Drinks and Cordials": "Jus de fruits",
        "Drinks - Soft Drinks": "Autres boissons",
        "Drinks Flavoured - Ready to Drink": "Autres boissons",
        "Coffee": "Autres boissons",
        "Coffee - Instant, Roast and Ground": "Autres boissons",
        "Coffee/Coffee Substitutes": "Autres boissons",
        "Coffee/Tea/Substitutes": "Autres boissons",
        "Baby Foods": "Aliments pour bébés",
        "Baby/Infant  Foods/Beverages": "Aliments pour bébés",
        "Baby/Infant – Foods/Beverages": "Aliments pour bébés",
        "Amino Acid Supplements": "Substituts de repas et suppléments",
        "Antioxidant Supplements": "Substituts de repas et suppléments",
        "Ayurvedic Supplements": "Substituts de repas et suppléments",
        "Digestive & Fiber Supplements": "Substituts de repas et suppléments",
        "Children's Nutritional Supplements": "Substituts de repas et suppléments",
        "Chips, Pretzels & Snacks": "Autres grignotines",
        "Chips/Crisps/Snack Mixes - Natural/Extruded (Shelf Stable)": "Autres grignotines",
        "Chocolate": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Chocolate and Chocolate/Sugar Candy Combinations - Confectionery": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Condiments, Oils & Dressing": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Confectionery": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Confectionery Products": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Cookies & Biscuits": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Cooking Oils and Fats": "Graisses et huiles non saturées",
        "Crackers & Biscotti": "Aliments non enrichis qui ne sont pas à grains entiers et de blé entier",
        "Croissants, Sweet Rolls, Muffins & Other Pastries": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Crusts & Dough": "Aliments non enrichis qui ne sont pas à grains entiers et de blé entier",
        "Doodles/ Puffs": "Autres grignotines",
        "Desserts & Custard": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Desserts (Frozen)": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Desserts (Shelf Stable)": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Desserts/Dessert Sauces/Toppings": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Deli and Chilled Foods": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Baking/Cooking Supplies (Shelf Stable)": "Aliments non enrichis qui ne sont pas à grains entiers et de blé entier",
        "Childcare": "Aliments pour bébés",
        "Children's Natural Remedies": "Substituts de repas et suppléments",
        "Chili & Stew": "Viandes transformées",
        "Canned Condensed Soup": "Autres aliments à base de lait",
        "Canned Soup": "Autres aliments à base de lait",
        "Condiments, Oils & Dressing": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Confection & Snacks": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Cooked & Prepared": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Dips & Salsa": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Dips - Shelf Stable": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Dressings/Dips (Shelf Stable)": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Dried Breads (Shelf Stable)": "Aliments non enrichis qui ne sont pas à grains entiers et de blé entier",
        "Dough Based Products / Meals": "Aliments non enrichis qui ne sont pas à grains entiers et de blé entier",
        "Dough Based Products / Meals - Not Ready to Eat - Savoury (Frozen)": "Aliments non enrichis qui ne sont pas à grains entiers et de blé entier",
        "Dough Based Products / Meals - Not Ready to Eat - Savoury (Shelf Stable)": "Aliments non enrichis qui ne sont pas à grains entiers et de blé entier",
        "Eggs & Egg Substitutes": "Oeufs",
        "Eggs Products/Substitutes": "Oeufs",
        "Eggs/Eggs Substitutes": "Oeufs",
        "Energy, Protein & Muscle Recovery Drinks": "Substituts de repas et suppléments",
        "Entrees, Sides & Small Meals": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Extracts/Salt/Meat Tenderisers (Shelf Stable)": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Fast Foods": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Fats Edible": "Graisses et huiles saturées et trans",
        "Fats and Oils": "Graisses et huiles non saturées",
        "Fatty Acid Supplements": "Substituts de repas et suppléments",
        "Finfish and Shellfish Products": "Poisson et fruits de mer",
        "Fish  Prepared/Processed": "Poisson et fruits de mer",
        "Fish  Unprepared/Unprocessed": "Poisson et fruits de mer",
        "Fish & Seafood": "Poisson et fruits de mer",
        "Fish - Prepared/Processed": "Poisson et fruits de mer",
        "Fish Substitutes": "Similis-viandes",
        "Fish – Prepared/Processed": "Poisson et fruits de mer",
        "Fish – Unprepared/Unprocessed": "Poisson et fruits de mer",
        "Flavored Rice Dishes": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Flavored Snack Crackers": "Autres grignotines",
        "Flour - Cereal/Pulse (Shelf Stable)": "Aliments non enrichis qui ne sont pas à grains entiers et de blé entier",
        "Flours & Corn Meal": "Aliments non enrichis qui ne sont pas à grains entiers et de blé entier",
        "Food/Beverage/Tobacco Variety Packs": "Aliments et boissons non classés (en raison de données manquantes)",
        "French Fries, Potatoes & Onion Rings": "Légumes féculents",
        "Fresh Chicken - Portions": "Volaille et oiseaux sauvages",
        "Fresh Chicken - Processed": "Viandes transformées",
        "Fresh Chicken - Whole": "Volaille et oiseaux sauvages",
        "Fresh Fruit and Vegetables": "Légumes et Fruits",
        "Fresh Meat": "Viandes rouges",
        "Fresh Meat, Poultry and Seafood": "Aliments protéinés d’origine animale",
        "Fresh Pasta": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Frozen Appetizers & Hors D'oeuvres": "Autres grignotines",
        "Frozen Bacon, Sausages & Ribs": "Viandes transformées",
        "Frozen Bread & Dough": "Aliments à grains entiers",
        "Frozen Breakfast Sandwiches, Biscuits & Meals": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Frozen Chicken - Portions": "Volaille et oiseaux sauvages",
        "Frozen Chicken - Processed": "Viandes transformées",
        "Frozen Desserts": "Autres aliments à base de lait",
        "Frozen Dinners & Entrees": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Frozen Fish & Seafood": "Poisson et fruits de mer",
        "Frozen Fish/Seafood": "Poisson et fruits de mer",
        "Frozen Foods": "Aliments et boissons non classés (en raison de données manquantes)",
        "Frozen Fruit": "Fruits",
        "Frozen Fruit & Fruit Juice Concentrates": "Jus de fruits",
        "Frozen Meals": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Frozen Meat": "Viandes rouges",
        "Frozen Pancakes, Waffles, French Toast & Crepes": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Frozen Patties and Burgers": "Viandes transformées",
        "Frozen Pies/Savouries": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Frozen Potato": "Légumes féculents",
        "Frozen Poultry, Chicken & Turkey": "Volaille et oiseaux sauvages",
        "Frozen Prepared Sides": "Aliments et boissons non classés (en raison de données manquantes)",
        "Frozen Sausages, Hotdogs & Brats": "Viandes transformées",
        "Frozen Snack": "Autres grignotines",
        "Frozen Vegetables": "Légumes",
        "Fruit": "Fruits",
        "Fruit  Prepared/Processed": "Fruits",
        "Fruit & Vegetable Juice, Nectars & Fruit Drinks": "Jus de fruits",
        "Fruit - Prepared/Processed": "Fruits",
        "Fruit - Prepared/Processed (Frozen)": "Fruits",
        "Fruit - Prepared/Processed (Shelf Stable)": "Fruits",
        "Fruit Juice - Not Ready to Drink (Frozen)": "Jus de fruits",
        "Fruit Juice - Ready to Drink (Shelf Stable)": "Jus de fruits",
        "Fruit – Prepared/Processed": "Fruits",
        "Fruit/Nuts/Seeds Combination": "Noix et graines",
        "Fruit/Nuts/Seeds Mixes - Prepared/Processed (Shelf Stable)": "Noix et graines",
        "Fruits  Unprepared/Unprocessed (Frozen)": "Fruits",
        "Fruits  Unprepared/Unprocessed (Shelf Stable)": "Fruits",
        "Fruits - Unprepared/Unprocessed (Frozen)": "Fruits",
        "Fruits - Unprepared/Unprocessed (Shelf Stable)": "Fruits",
        "Fruits and Fruit Juices": "Fruits",
        "Fruits, Vegetables & Produce": "Légumes et Fruits",
        "Fruits/Vegetables/Nuts/Seeds Variety Packs": "Légumes et Fruits",
        "Grain Based Products / Meals": "Aliments à grains entiers",
        "Grain Based Products / Meals - Not Ready to Eat - Savoury (Frozen)": "Aliments à grains entiers",
        "Grain Based Products / Meals - Not Ready to Eat - Savoury (Shelf Stable)": "Aliments à grains entiers",
        "Grains": "Grains entiers (100%)",
        "Grains/Cereal - Not Ready to Eat - (Shelf Stable)": "Aliments à grains entiers",
        "Grains/Cereal - Ready to Eat - (Shelf Stable)": "Aliments à grains entiers",
        "Grains/Flour": "Aliments à grains entiers",
        "Granulated, Brown & Powdered Sugar": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Gravy Mix": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Honey": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Jam, Jelly & Fruit Spreads": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Ketchup, Mustard, BBQ & Cheese Sauce": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Green Supplements": "Substituts de repas et suppléments",
        "Health Supplements and Vitamins": "Substituts de repas et suppléments",
        "Herbal Supplements": "Substituts de repas et suppléments",
        "Herbs & Spices": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Herbs And Spices": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Herbs/Spices (Shelf Stable)": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Herbs/Spices/Extracts": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Ham/Cold Meats": "Viandes transformées",
        "Lamb, Veal, and Game Products": "Viandes de gibier",
        "Legumes and Legume Products": "Légumineuses",
        "Lunch Snacks & Combinations": "Aliments et boissons non classés (en raison de données manquantes)",
        "Margarine/Butter": "Graisses et huiles saturées et trans",
        "Meat Substitutes": "Similis-viandes",
        "Meat/Poultry/Other Animals  Prepared/Processed": "Viandes transformées",
        "Meat/Poultry/Other Animals  Unprepared/Unprocessed": "Viandes rouges",
        "Meat/Poultry/Other Animals - Prepared/Processed": "Viandes transformées",
        "Meat/Poultry/Other Animals - Unprepared/Unprocessed": "Viandes rouges",
        "Meat/Poultry/Other Animals Sausages  Prepared/Processed": "Viandes transformées",
        "Meat/Poultry/Other Animals Sausages - Prepared/Processed": "Viandes transformées",
        "Meat/Poultry/Other Animals Sausages – Prepared/Processed": "Viandes transformées",
        "Meat/Poultry/Other Animals – Prepared/Processed": "Viandes transformées",
        "Meat/Poultry/Other Animals – Unprepared/Unprocessed": "Viandes rouges",
        "Ice Cream & Frozen Yogurt": "Autres aliments à base de lait",
        "Ice Cream/Ice Novelties (Shelf Stable)": "Autres aliments à base de lait",
        "Ice-Cream Take Home": "Autres aliments à base de lait",
        "Ice-Cream/Block Single": "Autres aliments à base de lait",
        "Ice-Cream/Ice-Block Multi Pack": "Autres aliments à base de lait",
        "Milk": "Laits",
        "Milk Additives": "Autres aliments à base de lait",
        "Milk/Cream": "Autres aliments à base de lait",
        "Iced & Bottle Tea": "Autres boissons",
        "Liquid Water Enhancer": "Autres boissons",
        "Infant Formula": "Aliments pour bébés",
        "Meal Replacement Supplements": "Substituts de repas et suppléments",
        "Meals, Entrees, and Side Dishes": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Mexican Dinner Mixes": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Gardening": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Health Care": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Home Decoration & Supplies": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Kitchen Supplies": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Media": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Milk/Cream - Shelf Stable": "Laits",
        "Milk/Milk Substitutes": "Laits",
        "Plant Based Milk": "Boissons végétales enrichies (qui ne contiennent pas suffisamment de protéines)",  # ex: lait d’amande, riz, coco
        "Processed Cheese & Cheese Novelties": "Fromages",
        "Nutritional Supplements": "Substituts de repas et suppléments",
        "Minerals": "Substituts de repas et suppléments",
        "Mussels": "Poisson et fruits de mer",
        "S/O Fresh Fish Fillets/Steaks": "Poisson et fruits de mer",
        "Non Alcoholic Beverages  Not Ready to Drink": "Autres boissons",
        "Non Alcoholic Beverages  Ready to Drink": "Autres boissons",
        "Non Alcoholic Beverages - Not Ready to Drink": "Autres boissons",
        "Non Alcoholic Beverages - Ready to Drink": "Autres boissons",
        "Non Alcoholic Beverages – Not Ready to Drink": "Autres boissons",
        "Non Alcoholic Beverages – Ready to Drink": "Autres boissons",
        "Powdered Drinks": "Autres boissons",
        "Ready To Drink": "Autres boissons",
        "Packaged Water": "Eau",
        "Plant Based Water": "Eau",
        "Other Drinks": "Autres boissons",
        "Nut & Seed Butters": "Noix et graines",
        "Nut and Seed Products": "Noix et graines",
        "Nuts/Seeds  Prepared/Processed": "Noix et graines",
        "Nuts/Seeds  Unprepared/Unprocessed (Shelf Stable)": "Noix et graines",
        "Nuts/Seeds - Prepared/Processed": "Noix et graines",
        "Nuts/Seeds - Prepared/Processed (Out of Shell)": "Noix et graines",
        "Nuts/Seeds - Prepared/Processed (Shelf Stable)": "Noix et graines",
        "Nuts/Seeds - Unprepared/Unprocessed (In Shell)": "Noix et graines",
        "Nuts/Seeds – Prepared/Processed": "Noix et graines",
        "Nuts/Seeds – Unprepared/Unprocessed (Shelf Stable)": "Noix et graines",
        "Oils Edible": "Graisses et huiles non saturées",
        "Oils Edible - Vegetable or Plant (Shelf Stable)": "Graisses et huiles non saturées",
        "Oriental, Mexican & Ethnic Sauces": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Other Condiments": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Other Cooking Sauces": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Other Sauces Dipping/Condiments/Savoury Toppings/Savoury Spreads/Marinades (Frozen)": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Other Sauces Dipping/Condiments/Savoury Toppings/Savoury Spreads/Marinades (Shelf Stable)": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Prepared Pasta & Pizza Sauces": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Salad Dressing & Mayonnaise": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Salad Dressings": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Sauces": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Sauces - Cooking (Frozen)": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Sauces - Cooking (Shelf Stable)": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Sauces- Cooking": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Sauces/Spreads/Dips/Condiments": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Pickles, Olives, Peppers & Relishes": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Pickles, Relishes and Vinegar": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Pickles/Relishes/Chutneys/Olives": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Pickled Vegetables": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Noodles": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Pasta": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Pasta - Instant Meals": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Pasta Dinners": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Pasta by Shape & Type": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Pasta/Noodles": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Pasta/Noodles - Not Ready to Eat (Frozen)": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Pancakes, Waffles, French Toast & Crepes": "Aliments non enrichis qui ne sont pas à grains entiers et de blé entier",
        "Rice": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Rice & Grains": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Processed Cereal Products": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Other Grains & Seeds": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Pizza Mixes & Other Dry Dinners": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Pork - Prepared/Processed": "Viandes transformées",
        "Pork - Unprepared/Unprocessed": "Viandes rouges",
        "Pork Products": "Viandes rouges",
        "Pork Sausages - Prepared/Processed": "Viandes transformées",
        "Poultry Products": "Volaille et oiseaux sauvages",
        "Poultry, Chicken & Turkey": "Volaille et oiseaux sauvages",
        "Salami / Cured Meat": "Viandes transformées",
        "Sausages and Luncheon Meats": "Viandes transformées",
        "Sausages, Hotdogs & Brats": "Viandes transformées",
        "Sausages/Smallgoods": "Viandes transformées",
        "Pepperoni, Salami & Cold Cuts": "Viandes transformées",
        "Other Meats": "Viandes rouges",
        "Other Frozen Meats": "Viandes rouges",
        "Pastries/Pies/Pizzas": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Pastry": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Pastry Shells & Fillings": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Pies/Pastries - Sweet (Frozen)": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Pies/Pastries - Sweet (Shelf Stable)": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Pies/Pastries/Pizzas/Quiches - Savoury (Frozen)": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Pizza": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Other Frozen Desserts": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Puddings & Custards": "Autres aliments à base de lait",
        "Puddings and desserts": "Autres aliments à base de lait",
        "Savoury Bakery Products": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Prepared Meals": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",
        "Ready-Made Combination Meals": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",
        "Ready-Made Combination Meals - Not Ready to Eat (Frozen)": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",
        "Prepared Subs & Sandwiches": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",
        "Prepared Wraps and Burittos": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",
        "Sandwiches/Filled Rolls/Wraps": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",
        "Sandwiches/Filled Rolls/Wraps (Frozen)": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",
        "Prepared/Preserved Foods Variety Packs": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",
        "Restaurant Foods": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",
        "Prepared Soups": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",
        "Other Soups": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",
        "Other Deli": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Other Pet Food": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Miscellanious": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Oral Hygiene Products": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Pre-Packaged Fruit & Vegetables": "Légumes et Fruits",
        "Salads": "Autres légumes",
        "Peppers": "Autres légumes",
        "Popcorn (Shelf Stable)": "Autres grignotines",
        "Popcorn, Peanuts, Seeds & Related Snacks": "Autres grignotines",
        "Seafood Miscellaneous": "Poisson et fruits de mer",
        "Shellfish Prepared/Processed": "Poisson et fruits de mer",
        "Shellfish Unprepared/Unprocessed": "Poisson et fruits de mer",
        "Smoked fish": "Poisson et fruits de mer",
        "Turkey - Prepared/Processed": "Volaille et oiseaux sauvages",
        "Turkey - Unprepared/Unprocessed": "Volaille et oiseaux sauvages",
        "Tofu": "Légumineuses",
        "Vegetarian": "Similis-viandes",
        "Vegetarian Frozen Meats": "Similis-viandes",
        "Sushi": "Poisson et fruits de mer",
        "Seasoning Mixes, Salts, Marinades & Tenderizers": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Seasonings/Preservatives/Extracts Variety Packs": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Spices and Herbs": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Vinegars/Cooking Wines": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Stuffing": "Condiments, sauces et vinaigrettes à faible teneur en matières grasses",
        "Soups - Prepared (Shelf Stable)": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",
        "Soups, Sauces, and Gravies": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",
        "Snack Foods - Cereal Snacks": "Autres grignotines",
        "Snack Foods - Chips": "Autres grignotines",
        "Snack Foods - Corn Chips": "Autres grignotines",
        "Snack Foods - Dried Fruit": "Autres grignotines",
        "Snack Foods - Multi Packs": "Autres grignotines",
        "Snack Foods - Nuts": "Noix et graines",
        "Snack Foods - Other": "Autres grignotines",
        "Snack, Energy & Granola Bars": "Autres grignotines",
        "Snacks": "Autres grignotines",
        "Snacks Other": "Autres grignotines",
        "Snacks Variety Packs": "Autres grignotines",
        "Wholesome Snacks": "Autres grignotines",
        "Wrapped Snacks - Cereal": "Autres grignotines",
        "Wrapped Snacks - Fruit Bars": "Autres grignotines",
        "Wrapped Snacks - Muesli Bars": "Autres grignotines",
        "Wrapped Snacks - Nut Bars": "Autres grignotines",
        "Sweet Bakery Products": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Sweet Spreads": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Sweets": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Syrups & Molasses": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Sugar Candy/Sugar Candy Substitutes Confectionery": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Sugars/Sugar Substitute Products": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Sugar And Flour": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Soda": "Autres boissons",
        "Sport Drinks": "Autres boissons",
        "Tea - Bags, Loose Leaf, Speciality": "Autres boissons",
        "Tea Bags": "Autres boissons",
        "Tea and Infusions/Tisanes": "Autres boissons",
        "Water": "Eau",
        "Tomatoes": "Autres légumes",
        "Vegetable & Cooking Oils": "Graisses et huiles non saturées",
        "Vegetable Based Products / Meals": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",
        "Vegetable Based Products / Meals - Not Ready to Eat (Frozen)": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",
        "Vegetable Based Products / Meals - Not Ready to Eat (Shelf Stable)": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",
        "Vegetable and Lentil Mixes": "Légumineuses",
        "Vegetables": "Légumes",
        "Vegetables Prepared/Processed": "Autres légumes",
        "Vegetables Unprepared/Unprocessed (Frozen)": "Autres légumes",
        "Vegetables Unprepared/Unprocessed (Shelf Stable)": "Autres légumes",
        "Vegetables - Prepared/Processed": "Autres légumes",
        "Vegetables - Prepared/Processed (Frozen)": "Autres légumes",
        "Vegetables - Prepared/Processed (Shelf Stable)": "Autres légumes",
        "Vegetables - Unprepared/Unprocessed (Frozen)": "Autres légumes",
        "Vegetables - Unprepared/Unprocessed (Shelf Stable)": "Autres légumes",
        "Vegetables and Vegetable Products": "Autres légumes",
        "Vegetables – Prepared/Processed": "Autres légumes",
        "Vegetables – Unprepared/Unprocessed (Frozen)": "Autres légumes",
        "Vegetables – Unprepared/Unprocessed (Shelf Stable)": "Autres légumes",
        "Yogurt": "Yogourts et kéfir",
        "Yogurt (Perishable)": "Yogourts et kéfir",
        "Yogurt/Yogurt Substitutes": "Yogourts végétaux",
        "Yogurt/Yogurt Substitutes (Perishable)": "Yogourts végétaux",
        "Specialty Formula Supplements": "Substituts de repas et suppléments",
        "Sports and Weight Management": "Substituts de repas et suppléments",
        "Vitamins": "Substituts de repas et suppléments",
        "Vitamins/Minerals/Nutritional Supplements": "Substituts de repas et suppléments",
        "Weight Control": "Substituts de repas et suppléments",
        "Skin Care Preparations": "Aliments divers (les ingrédients, les fines herbes, les épices, les bonbons sans sucre, les mélanges non préparés)",
        "Includes all products which can be described/observed as a healthy food alternative to meat vegetable and egg proteins. These products are non animal based and an imitation of meat products, meant to simulate the taste and mouthfeel of real meat but are normally made from a combination of non animal based ingredients. Includes products such as soya, fungus, beans, lentils, peas and chickpeas based products. These products must be frozen to extend their consumable life.": "Similis-viandes",
        "Includes any products that can be described/observed as a cereal combining all or some of the following ingredients: oats, muesli, wheat, rice, seeds, bran, fruit, nuts, cereal and honey, which has gone through further manufacturing processes such as cooking, milling, drying and reforming, which will require preparation/cooking prior to consumption. Includes products such as porridge oats, couscous and tapioca. These products have been treated or packaged in such a way as to extend their consumable life.": "Aliments à grains entiers",

        "Includes any products that can be described/observed as a fine powder derived from grains, roots or tubers. These products have been treated or packaged in such a way as to extend their consumable life. Specifically excludes products such as Cornflour. Excludes products such as Whole Grains, Bread and Baking Mixes.": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",

        "Includes any products that can be described/observed as a food made from ground pork, which may be prepared using a specific, regionally based process. The ground meat is mixed with other ingredients such as animal fat, salt, spices, herbs, vegetables or fruit and then typically packed in a casing, which may be link shaped or form a rope or ring, or sold without a casing such as bologna and some frankfurters. Some sausages are cooked during processing and may be preserved by curing, drying in cool air, or smoking.": "Viandes transformées",

        "Includes any products that can be described/observed as a food made from ground turkey meat, which may be prepared using a specific, regionally based process. The ground meat is mixed with other ingredients such as animal fat, salt, spices, herbs, vegetables or fruit and then typically packed in a casing, which may be link shaped or form a rope or ring, or sold without a casing such as bologna and some frankfurters. Some sausages are cooked during processing and may be preserved by curing, drying in cool air, or smoking.": "Viandes transformées",

        "Includes any products that can be described/observed as a frozen substance, which can be heated and combined with other ingredients, such as pasta, rice and chicken, to produce a specific recipe, such as Bolognese, Carbonara, Chicken Korma or Thai Curry.": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",

        "Includes any products that can be described/observed as a leavened or unleavened, dough-based baked product. These products do not typically contain eggs and tend to have lower fat content than other dough products such as pastry. These products must be frozen to extend their consumable life. Includes such products as naan, chapatti, loaves, rolls, bagels, focaccia, ciabatta, baguette. Also includes rye bread, bread made from rice flour and part baked bread products.": "Aliments à grains entiers",

        "Includes any products that can be described/observed as a leavened or unleavened, dough-based baked product. These products do not typically contain eggs and tend to have lower fat content than other dough products such as pastry. These products must be frozen to extend their consumable life. Includes such products as naan, chapatti, loaves, rolls, bagels, focaccia, ciabatta, baguette. Also includes rye bread, bread made from rice flour and part baked bread products. Excludes products such as Shelf-Stable and Perishable Bread Products, Dried Breads, Frozen Baking Mixes and Baking Supplies, and Pies and Pastries.": "Aliments à grains entiers",

        "Includes any products that can be described/observed as a liquid food made from the stock of meat, fish and/or vegetables, which may also contain some small solid pieces of meat, fish and/or vegetables. These products must be frozen to extend their consumable life.": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",

        "Includes any products that can be described/observed as a pastry, biscuit or crumble based product filled or topped with a mixture of shredded/sliced savoury ingredients, commonly including meat, vegetables, eggs or other additive. Products must be frozen to extend their consumable life. Excludes products such as Perishable and Shelf Stable Savoury Pies, Pastries, Pizzas and Quiches, Sweet Pies/Tarts, and Potato Topped Meat Pies.": "Autres grignotines",

        "Includes any products that can be described/observed as a prepared food normally consumed as the last course of a meal. These products have been packaged in such a way as to extend their consumable life. Products include desserts that are biscuit based, bread based, cake/sponge based, dairy based, pastry based and rice based. Excludes products such as Perishable and Frozen Desserts, Ice Cream, Pastries and Cakes, Yogurt.": "Aliments à teneur plus élevée en sucre et/ou en gras",

        "Includes any products that can be described/observed as a quantity of perishable, pre-mixed dough, batter or powder or other ingredients that is specifically intended to produce bread, cakes, biscuits, desserts, or other products. Products may be ready to use (where no additional ingredients need to be added to the mix prior to use) or require the addition of wet ingredients such as water, milk, oil, fat or egg. These products must be refrigerated to extend their consumable life. Excludes products such as Soups, Frozen or Shelf-Stable Baking Mixes, all Part Baked and Baked Products.": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",

        "Includes any products that can be described/observed as a quantity of shelf-stable, pre-mixed dough, batter or powder that is specifically intended to produce bread, cakes, biscuits, desserts, or other products. Products may be ready to use (where no additional ingredients need to be added to the mix prior to use) or require the addition of wet ingredients such as water, milk, oil, fat or egg. These products have been treated or packaged in such a way as to extend their consumable life. Excludes products such as Soups, Frozen or Perishable Baking Mixes, all Part Baked and Baked Products.": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",

        "Includes any products that can be described/observed as a savoury dough-based not ready to eat, prepared/processed product, such as Pasta, Gnocchi, Noodles or Batter, with other ingredients, such as meat, dairy, eggs, fish, vegetables and/or seasoning. An optional seasoning/flavour packet may be present. These ingredients form a valuable part of the product, such as the meat/tomato sauce in Spaghetti Bolognaise, or cheese sauce in Macaroni and Cheese. They may or may not contain a sauce. These products are not ready to eat and require cooking prior to consumption. These products may have a main component which is considered a meal without any additional components. These products must be fro": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",

        "Includes any products that can be described/observed as a substance which can be heated and combined with other ingredients, such as pasta, rice and chicken, to produce a specific recipe, such as Bolognese, Carbonara, Chicken Korma or Thai Curry. These products have been treated or packaged in such a way as to extend their consumable life. Excludes products such as Sauces Dipping and Condiments and Savoury Spreads and Marinades, Perishable and Frozen Sauces Cooking.": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",

        "Includes any products that can be described/observed as frozen food made from the curd of milk, separated from the whey, sometimes fermented, and usually pressed, cooked, smoked, matured, or heated and mixed with artificial ingredients, such as emulsifiers, colourings and flavourings. These products must be frozen to extend their consumable life. These products include natural, processed cheese, cheese with added ingredients, such as herbs and nuts, in blocks, rolls, slices, grated, cubes, spreadable and portions.": "Autres aliments à base de lait",

        "Includes products from animals of the domestic pig ( Sus Scrofa Domesticus) that have been subjected to one or more further manufacturing processes such as being cooked, dried, cured, ground, or reformed.": "Viandes rouges",
        "Includes products from animals of the species Gallus gallus domesticus that have been subjected to one or more further manufacturing processes such as being cooked, dried, cured, ground, or reformed.": "Volaille et oiseaux sauvages",
        "Includes products from animals of the species Meleagris gallopavo that have been subjected to one or more further manufacturing processes such as being cooked, dried, cured, ground, or reformed.": "Volaille et oiseaux sauvages",
        "Includes products from mature animals of the genus Bos that have been subjected to one or more further manufacturing processes such as being cooked, dried, cured, ground, or reformed.": "Viandes rouges",

        "Ready-made combination meal, frozen dinner, frozen meal, or microwave meal is a pre-packaged frozen full meal.  The meal requires no preparation other than cooking and contains all the elements typically contained in a single-serving meal.  A ready-made meal (also known as a TV Dinner) must have a main component and at least one additional component such as a side item, a dessert and/or beverage. These products require cooking prior to consumption. These products must be frozen to extend their consumable life.": "Autres aliments d’origine végétale (qui contiennent suffisamment de protéines)",
        "Chewing Gum & Mints": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Canned & Bottled Beans": "Légumineuses",
        "Vegetables Prepared/Processed": "Légumes",
        "Cake, Cookie & Cupcake Mixes": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Other Snacks": "Autres grignotines",
        "Bread/Bakery Products Variety Packs": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Breakfast Drinks": "Autres boissons",
        "Cake, Cookie & Cupcake Mixes": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Canned & Bottled Beans": "Légumineuses",
        "Cheese - Speciality ": "Fromages",
        "Chewing Gum & Mints": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Drinks - Energy Drinks": "Autres boissons",
        "Drinks - Powdered": "Autres boissons",
        "Fruits": "Fruits",
        "Gelatin, Gels, Pectins & Desserts": "Aliments à teneur plus élevée en sucre et/ou en gras",
        "Includes any products that can be described/observed as frozen food made from the curd of milk, separated from the whey, sometimes fermented, and usually pressed, cooked, smoked, matured, or heated and mixed with artificial ingredients, such as emulsifiers, colourings and flavourings. These products must be frozen to extend their consumable life. These products include natural, processed cheese, cheese with added ingredients, such as herbs and nuts, in blocks, rolls, slices, grated, cubes, spreadable and portions. Excludes products such as Shelf Stable and Perishable Cheeses, all Cheese Substitutes and Cheese-Based/Flavoured Meals.": "Fromages",
        "Includes products from animals of the domestic pig ( Sus Scrofa Domesticus) that have been subjected to one or more further manufacturing processes such as being cooked, dried, cured, ground, or reformed. Specifically excludes Meat/Poultry Sausages - Prepared/Processed. Excludes Pork - Unprepared/Unprocessed.": "Viandes transformées",

        "Includes products from animals of the species Gallus gallus domesticus that have been subjected to one or more further manufacturing processes such as being cooked, dried, cured, ground, or reformed. Specifically excludes Meat/Poultry Sausages - Prepared/Processed. Excludes Chicken - Unprepared/Unprocessed.": "Volaille et oiseaux sauvages",

        "Includes products from mature animals of the genus Bos that have been subjected to one or more further manufacturing processes such as being cooked, dried, cured, ground, or reformed. Specifically excludes Meat/Poultry Sausages - Prepared/Processed. Excludes Beef - Unprepared/Unprocessed.": "Viandes rouges",

        "Other Snacks": "Autres grignotines",
        "Potato - Instant Meals": "Légumes féculents",
        "Spreads": "Graisses et huiles non saturées",
        "Taco Shells": "Aliments enrichis qui ne sont pas à grains entiers et de blé entier",
        "Vegetables  Prepared/Processed": "Autres légumes",
        "Vegetables  Unprepared/Unprocessed (Frozen)": "Autres légumes",
        "Vegetables  Unprepared/Unprocessed (Shelf Stable)": "Autres légumes",
    }

    total_updates = 0
    bulk_ops = []

    # Un seul parcours complet de la collection
    for doc in collection_name.find({"food_groups": {"$exists": True}}, {"food_groups": 1}):
        fg = doc.get("food_groups")
        if fg in mapping:
            category_ca = mapping[fg]
            bulk_ops.append(
                {
                    "filter": {"_id": doc["_id"]},
                    "update": {"$set": {"category_ca": category_ca,"category_code_ca" : categories_and_code_ca[category_ca]}}
                    
                }
            )

    # Envoi en bulk
    if bulk_ops:
        from pymongo import UpdateOne
        result = collection_name.bulk_write([UpdateOne(op["filter"], op["update"]) for op in bulk_ops])
        total_updates = result.modified_count
        print(f"✅ {total_updates} documents mis à jour avec 'category_ca'.")

    else:
        print("⚠️ Aucun document à mettre à jour.")

    # client.close()


if __name__ == "__main__":
    rename_food_groups_fdc()
